name: daily-raw-archive

on:
  schedule:
    # 12:00 PM IST = 06:30 UTC
    - cron: "30 6 * * *"
  workflow_dispatch: {}   # allows manual runs too

permissions:
  contents: write

jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run archiver
        run: python scraper/archive_daily.py

      - name: Commit snapshots
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add "data/."
          git commit -m "Daily snapshot: $(date -u +'%Y-%m-%d %H:%M:%S') UTC" || echo "No changes to commit"
          git push
