name: daily-raw-pdfs

on:
  schedule:
    # 12:00 PM IST = 06:30 UTC
    - cron: "30 6 * * *"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ---- Python: make folder (IST) + save HDFC PDF ----
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run archiver (HDFC_Rates.pdf)
        run: python scraper/archive_daily.py

      - name: Tree before PDF step
        run: |
          echo "== Files BEFORE Node PDF step =="
          find "data/Currency Raw Data" -maxdepth 5 -type f -print || true

      # ---- Node: render AXIS & ICICI to PDF with Puppeteer ----
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # Install common Chrome dependencies that Puppeteer needs on ubuntu-latest
      - name: Install Chromium dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libnss3 libxss1 libasound2 fonts-liberation \
            libatk1.0-0 libatk-bridge2.0-0 libcups2 libdrm2 \
            libxkbcommon0 libxcomposite1 libxdamage1 libxfixes3 \
            libglib2.0-0 libgtk-3-0 libpango-1.0-0 libcairo2 \
            libatspi2.0-0

      - name: Install Puppeteer
        working-directory: scraper
        run: |
          npm init -y
          npm install puppeteer

      - name: Render AXIS & ICICI PDFs
        working-directory: scraper
        run: node save_pdf.js

      - name: Tree after PDF step
        run: |
          echo "== Files AFTER Node PDF step =="
          find "data/Currency Raw Data" -maxdepth 6 -type f -print || true

      # ---- Commit PDFs ----
      - name: Commit daily PDFs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add "data/."
          git commit -m "Daily PDFs: $(date -u +'%Y-%m-%d %H:%M:%S') UTC" || echo "No changes to commit"
          git push

      # Optional: also upload as artifact for easy download/debug
      - name: Upload day folder artifact
        uses: actions/upload-artifact@v4
        with:
          name: day-folder
          path: |
            data/Currency Raw Data/**/*
